// Real Decdock run - Enron public FERC archive (250 emails -> curated proof subset).
const META = {
  "source": "decdock-enron-run2-moat",
  "sourceKind": "decdock.knowledge.raw.v1",
  "tenant": "enron-energy-trading",
  "generatedAt": "2026-07-02T11:12:51.249Z",
  "rawRecords": 316,
  "rawExtractedItems": 441,
  "rawConflicts": 6,
  "rawSupersedes": 22,
  "curatedRecords": 41,
  "keptConflicts": 5,
  "keptSupersedes": 2,
  "driftEdges": 7,
  "droppedConflicts": 1,
  "droppedSupersedes": 20,
  "honestyNote": "Supersedes edges are kept only when newer.sourceDate is later than older.sourceDate and the edge explanation is not a system heuristic. Borderline UK TWh and Mahonia sequence edges are dropped."
};

const SOURCES = {
  "limit": {
    "sub": "Trading limits",
    "body": "ENRON - public email archive (FERC)\nTrading limits\n\n[2000-04-10] Re: Limit Violation - Enron Australia\nit would be somewhat unprecedented to leave a \"proprietary\" position over the limit for that length of time, i.e., the Australian Electricity book would far exceed the number of position limit violations for any other commodities\n\n[2000-04-10] Re: Limit Violation - Enron Australia\nyou put together a request for approval to increase your limits to be presented at the first opportunity\n\n[2000-05-24] Personal Achievement Award (PAA) Program\nThe maximum award is $2,000. Awards over $2,000 maximum require Chairman approval\n\n[2000-12-27] Summary of Changes to Trading Limits 12/7 - 1/6\nUK Power 68 Twh 68 Twh 59.5 Twh 59.5 Twh\n\n[2001-02-13] Global Markets Limits\nA separate e-mail was sent to each of your head traders and business unit controllers/CAO for each of these commodity groups with limit changes.\n\n[2001-06-29] Important eProcurement Information\nNote: if the shopping cart exceeds your spend limit, or contains fleet, stand-by or IT hardware items it will require additional approval/review."
  },
  "var": {
    "sub": "Risk / VaR",
    "body": "ENRON - public email archive (FERC)\nRisk / VaR\n\n[2000-06-12] Violation Memos Distribution\nDaily Loss 50% - 75% of VAR Limit > 75% of VAR Limit (VAR Limit = $40 MM); 5-Day Cumulative Loss 75% - 100% of VAR Limit > VAR Limit\n\n[2000-12-12] Enron Europe Limit Changes and DPR Reporting\nDaily Loss in any Commodity group or Portfolio: Report to Business Unit Office of the Chairman 100% of VaR... Report to Enron Corp. President 125% of VaR... Report to Enron Corp. Chairman 150% of VaR... Report to Audit Committee no reporting at commodity group level\n\n[2000-12-12] Enron Europe Limit Changes and DPR Reporting\nCumulative 5-day Loss in any Commodity Group or Portfolio: Report to Business Unit Office of the Chairman 125% of VaR... Report to Enron Corp. President 150% of VaR... Report to Enron Corp. Chairman 175% of VaR... Report to Audit Committee no reporting at commodity group level\n\n[2000-12-19] Upcoming Limit Changes- UK Power\nUK Power's VaR and NOP are as follows: 1/1/01 - 1/5/01 UK Power VaR $13.95MM\n\n[2000-12-27] Summary of Changes to Trading Limits 12/7 - 1/6\nUK Power $20.3MM $20.3MM $18.95MM $13.95MM\n\n[2001-08-16] Policy and other items\nThe BOD approved an aggregate of $150MM, with $50MM of discretionary VaR, plus the new policy which doesn't recognise the concept of discretionary VaR.\n\n[2001-08-16] Policy and other items\nAt Business Unit level the individual commodity limits are unchanged, and I have put limits over the Business Units themselves as follows: Enron Americas $82MM, EWS OOC (aka George Martingale) $3MM, EEL $34MM, EGM $23MM, EIM $8MM, EBS $4MM, PGE $4MM, ETS $1MM.\n\n[2001-08-16] Policy and other items\nTotal trading was a loss of $106MM against a VaR limit of $150MM so no calls to Pug required (thank goodness).\n\n[2001-08-28] Limit Revision - Enron Americas\nReplace with one limit, expressed in VaR, for the entire business unit, of $100MM. ETL at this level could be in the region of $340MM."
  },
  "dpr": {
    "sub": "DPR & loss notification",
    "body": "ENRON - public email archive (FERC)\nDPR & loss notification\n\n[2000-06-12] Violation Memos Distribution\nMark Frevert and Joe Sutton have asked to be copied on all violation memos and loss notification memos.\n\n[2000-06-26] Quarter-end DPR Process\nAdjustments > $250,000 require approval from John Lavorato or John Sherriff.\n\n[2000-06-26] Quarter-end DPR Process\nNO DPR will be issued dated July 3, 2000. For divisions reporting P&L for July 3rd and/or July 4th, a 'Special DPR' will be issued on July 5th... For consolidated DPR purposes, July 3rd and July 4th will be combined and reported as one day. These combined days will be reported as July 4th.\n\n[2000-12-06] DPR and Loss Notification - \"Structured Derivatives\"\nChris, please include this loss in today's notification letters to Ken Lay and Jeff Skilling for the 5th. Per Oliver, the loss was due to power price curve shift and gas volatility curve shift against the Eastern spread options.\n\n[2000-12-12] Enron Europe Limit Changes and DPR Reporting\nEuropean Gas - NOP and Maturity/Gap Limits revert to permanent limits on 1/1/01 (as previously scheduled), of 60 Bcf and 90 Bcf, respectively\n\n[2001-02-13] NA Gas and Power Limits\nClarify the cross-commodity trading policy to specify that trading limits are to be applied against Enron's consolidated commodity positions on an individual commodity group basis; Enron's consolidated Daily Position Report should provide required market risk disclosures by primary commodity group"
  },
  "reg": {
    "sub": "Regulation",
    "body": "ENRON - public email archive (FERC)\nRegulation\n\n[2000-06-15] *** INTERRUPTIBLE CUSTOMERS CAN PARTICIPATE IN ISO A/S PROGRAM ***\nComments are due on June 27. Unless you tell us otherwise, we plan to file and seek expedited treatment... Both have asked for a July 17 effective date.\n\n[2000-07-01] TW Capacity Options meeting\nsales of options require Board approval at Enron\n\n[2001-09-10] Redrock Permit Issue, Requested Information\nEither Bill Kendrick or I will be touching base with her again, tomorrow. The EPA contact for the Sta. 3 and 4 air permits: permit engineer Roger Cohn\n\n[2002-02-20] NAESB EC Meeting\nA vote will be taken to change the version 1.5 'GISB' standards to 'NAESB' standards... It will probably be a 17/2 vote... people will want to make it clear that this 17/2 vote should not be interpreted as a vote in favor of each and every standard. It is only a vote in favor of changing the...\n\n[2002-02-20] NAESB EC Meeting\nThe plan is to bring the response document before the Board at their March meeting for 'approval'. The response should also be reviewed by the Editorial Review Board... They may want the EC to approve the 'Executive Summary' and 'Conclusion' (total 3 pages). I have no problem with that vote except..."
  },
  "people": {
    "sub": "HR / benefits",
    "body": "ENRON - public email archive (FERC)\nHR / benefits\n\n[2000-08-22] Re: Approval for Sign on Bonuses\nIf the sign on bonus amount is substantial then approval from David Oxley is advisable. In our current case, a $5,000.00 sign on for a Sr. Specialist would not require additional approval except your own.\n\n[2000-08-22] Re: Approval for Sign on Bonuses\nIf you are primarily in agreement regarding a small sign on bonus award, then no further approval process is necessary. If the sign on bonus amount is substantial then approval from David Oxley is advisable.\n\n[2001-11-29] REVISED DRAFT - Savings Plan Memo\nAfter November 30, Enron will no longer match your savings plan contributions. As an exception, the company will continue to match union employees' contributions to the Plan.\n\n[2001-11-29] REVISED DRAFT - Savings Plan Memo\nSavings Plan contributions that are deducted from your November 30 paycheck will be matched by Enron in cash rather than Enron stock. The cash match will be placed into the Fidelity Freedom 2000 fund, the default fund for the Plan.\n\n[2001-11-29] REVISED DRAFT - Savings Plan Memo\nDiversification within the Plan will now be allowed, regardless of your age, from ALL company contribution accounts... Effective immediately, you can invest these amounts in the fund or funds of your choosing."
  },
  "ops": {
    "sub": "Operations",
    "body": "ENRON - public email archive (FERC)\nOperations\n\n[2000-10-09] Signature authority\nhe can approve but can't sign as a director. You need to continue to manage. This would take a board resolution to change\n\n[2001-01-31] Approval of a Non-Solicitation Provision\nPursuant to an Interoffice Memorandum from Jim Derrick to all Enron Attorneys dated October 27, 1999, I am required to seek approval from each of you prior to signing off on a non-solicitation agreement which affects Enron North America Corp."
  },
  "credit": {
    "sub": "Counterparty / credit",
    "body": "ENRON - public email archive (FERC)\nCounterparty / credit\n\n[2000-10-26] OGC/AGC Approval Policy for More Than One Year Contracts\nIf a master is in place, confirmations will be used for terms of one month to greater than one year. I don't think it will be practical for us to approve these confirmations before signature unless there are material modifications done to the pre-approved confirmation template in the master, which...\n\n[2001-08-10] London Update\n2 risk policy issues came up - one regarding credit trading and the other regarding the freight book wanting to lay off credit risk with the credit book\n\n[2002-01-24] Message from Ken Lay\nEarlier today, I stepped down as Enron's Chairman of the Board and Chief Executive Officer. This decision was reached in cooperation with Enron's Board and the Creditor Committee and is effective immediately. The Creditor Committee has begun a search for a restructuring specialist to serve as..."
  },
  "dash": {
    "sub": "DASH deal approval",
    "body": "ENRON - public email archive (FERC)\nDASH deal approval\n\n[2000-11-13] Deal Approval Sheet (DASH) Process\nAll transactions (capital expenditures or risk adjusted capital) in excess of $500,000 must have a completed DASH and sign off by the following groups: applicable EGM business unit management, EGM Office of the Chairman, Legal, RAC, EGM Operations, Enron Capital Management, appropriate level of...\n\n[2000-11-13] Deal Approval Sheet (DASH) Process\nCapital expenditures include any acquisitions/divestitures of assets, offerings of debt, subordinated debt, equity or partnership capital or entering into a commodity or financial position that results in an exposure outside of Board approved limits. Capital expenditure amounts embedded in a...\n\n[2000-11-14] Deal Approval Sheet (DASH) Process for EGM\nAll transactions (capital expenditures or risk adjusted capital) in excess of $500,000 must have a completed DASH and sign off by the following groups: applicable EGM business unit management, EGM Office of the Chairman, Legal, RAC, EGM Operations, Enron Capital Management, appropriate level of...\n\n[2000-11-14] Deal Approval Sheet (DASH) Process for EGM\nentering into a commodity or financial position that results in an exposure outside of Board approved limits. Capital expenditure amounts embedded in a commodity price to a counterparty should be analyzed separately for DASH purposes and authorized by the appropriate entity\n\n[2001-11-12] Dash Sign Off\nEffective immediately, I want to sign all Dashes for RAC. I have asked Dave to continue reviewing the deals and initial the Dash but I want to sign them."
  }
};

const DATA = [
  {
    "id": "rec-0078",
    "kind": "politika",
    "st": "onayli",
    "d": "it would be somewhat unprecedented to leave a \"proprietary\" position over the limit for that...",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2000-04-10",
    "sk": "limit",
    "hl": "it would be somewhat unprecedented to leave a \"proprietary\" position over the limit for that length of time, i.e., the Australian Electricity book would far exceed the number of position limit violations for any other commodities"
  },
  {
    "id": "rec-0080",
    "kind": "karar",
    "st": "onayli",
    "d": "you put together a request for approval to increase your limits to be presented at the first...",
    "o": "Rick Buy",
    "os": "ratifier",
    "c": "high",
    "date": "2000-04-10",
    "sk": "limit",
    "hl": "you put together a request for approval to increase your limits to be presented at the first opportunity"
  },
  {
    "id": "rec-0424",
    "kind": "politika",
    "st": "onayli",
    "d": "The maximum award is $2,000. Awards over $2,000 maximum require Chairman approval",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2000-05-24",
    "sk": "limit",
    "hl": "The maximum award is $2,000. Awards over $2,000 maximum require Chairman approval"
  },
  {
    "id": "rec-0070",
    "kind": "politika",
    "st": "onayli",
    "d": "Daily Loss 50% - 75% of VAR Limit > 75% of VAR Limit (VAR Limit = $40 MM); 5-Day Cumulative...",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2000-06-12",
    "sk": "var",
    "hl": "Daily Loss 50% - 75% of VAR Limit > 75% of VAR Limit (VAR Limit = $40 MM); 5-Day Cumulative Loss 75% - 100% of VAR Limit > VAR Limit"
  },
  {
    "id": "rec-0071",
    "kind": "karar",
    "st": "onayli",
    "d": "Mark Frevert and Joe Sutton have asked to be copied on all violation memos and loss...",
    "o": "Mark Frevert",
    "os": "ratifier",
    "c": "high",
    "date": "2000-06-12",
    "sk": "dpr",
    "hl": "Mark Frevert and Joe Sutton have asked to be copied on all violation memos and loss notification memos."
  },
  {
    "id": "rec-0006",
    "kind": "politika",
    "st": "onayli",
    "d": "Comments are due on June 27. Unless you tell us otherwise, we plan to file and seek expedited...",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2000-06-15",
    "sk": "reg",
    "hl": "Comments are due on June 27. Unless you tell us otherwise, we plan to file and seek expedited treatment... Both have asked for a July 17 effective date."
  },
  {
    "id": "rec-0063",
    "kind": "karar",
    "st": "onayli",
    "d": "Adjustments > $250,000 require approval from John Lavorato or John Sherriff.",
    "o": "John Lavorato",
    "os": "ratifier",
    "c": "high",
    "date": "2000-06-26",
    "sk": "dpr",
    "hl": "Adjustments > $250,000 require approval from John Lavorato or John Sherriff."
  },
  {
    "id": "rec-0064",
    "kind": "politika",
    "st": "onayli",
    "d": "NO DPR will be issued dated July 3, 2000. For divisions reporting P&L for July 3rd and/or July...",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2000-06-26",
    "sk": "dpr",
    "hl": "NO DPR will be issued dated July 3, 2000. For divisions reporting P&L for July 3rd and/or July 4th, a 'Special DPR' will be issued on July 5th... For consolidated DPR purposes, July 3rd and July 4th will be combined and reported as one day. These combined days will be reported as July 4th."
  },
  {
    "id": "rec-0310",
    "kind": "politika",
    "st": "onayli",
    "d": "sales of options require Board approval at Enron",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2000-07-01",
    "sk": "reg",
    "hl": "sales of options require Board approval at Enron"
  },
  {
    "id": "rec-0020",
    "kind": "karar",
    "st": "onayli",
    "d": "If the sign on bonus amount is substantial then approval from David Oxley is advisable. In our...",
    "o": "Sally Beck",
    "os": "ratifier",
    "c": "high",
    "date": "2000-08-22",
    "sk": "people",
    "hl": "If the sign on bonus amount is substantial then approval from David Oxley is advisable. In our current case, a $5,000.00 sign on for a Sr. Specialist would not require additional approval except your own."
  },
  {
    "id": "rec-0021",
    "kind": "politika",
    "st": "onayli",
    "d": "If you are primarily in agreement regarding a small sign on bonus award, then no further...",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2000-08-22",
    "sk": "people",
    "hl": "If you are primarily in agreement regarding a small sign on bonus award, then no further approval process is necessary. If the sign on bonus amount is substantial then approval from David Oxley is advisable."
  },
  {
    "id": "rec-0269",
    "kind": "politika",
    "st": "onayli",
    "d": "he can approve but can't sign as a director. You need to continue to manage. This would take a...",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2000-10-09",
    "sk": "ops",
    "hl": "he can approve but can't sign as a director. You need to continue to manage. This would take a board resolution to change"
  },
  {
    "id": "rec-0398",
    "kind": "politika",
    "st": "onayli",
    "d": "If a master is in place, confirmations will be used for terms of one month to greater than one...",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2000-10-26",
    "sk": "credit",
    "hl": "If a master is in place, confirmations will be used for terms of one month to greater than one year. I don't think it will be practical for us to approve these confirmations before signature unless there are material modifications done to the pre-approved confirmation template in the master, which..."
  },
  {
    "id": "rec-0123",
    "kind": "politika",
    "st": "onayli",
    "d": "All transactions (capital expenditures or risk adjusted capital) in excess of $500,000 must...",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2000-11-13",
    "sk": "dash",
    "hl": "All transactions (capital expenditures or risk adjusted capital) in excess of $500,000 must have a completed DASH and sign off by the following groups: applicable EGM business unit management, EGM Office of the Chairman, Legal, RAC, EGM Operations, Enron Capital Management, appropriate level of..."
  },
  {
    "id": "rec-0124",
    "kind": "politika",
    "st": "onayli",
    "d": "Capital expenditures include any acquisitions/divestitures of assets, offerings of debt,...",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2000-11-13",
    "sk": "dash",
    "hl": "Capital expenditures include any acquisitions/divestitures of assets, offerings of debt, subordinated debt, equity or partnership capital or entering into a commodity or financial position that results in an exposure outside of Board approved limits. Capital expenditure amounts embedded in a..."
  },
  {
    "id": "rec-0393",
    "kind": "politika",
    "st": "onayli",
    "d": "All transactions (capital expenditures or risk adjusted capital) in excess of $500,000 must...",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2000-11-14",
    "sk": "dash",
    "hl": "All transactions (capital expenditures or risk adjusted capital) in excess of $500,000 must have a completed DASH and sign off by the following groups: applicable EGM business unit management, EGM Office of the Chairman, Legal, RAC, EGM Operations, Enron Capital Management, appropriate level of..."
  },
  {
    "id": "rec-0394",
    "kind": "politika",
    "st": "onayli",
    "d": "entering into a commodity or financial position that results in an exposure outside of Board...",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2000-11-14",
    "sk": "dash",
    "hl": "entering into a commodity or financial position that results in an exposure outside of Board approved limits. Capital expenditure amounts embedded in a commodity price to a counterparty should be analyzed separately for DASH purposes and authorized by the appropriate entity"
  },
  {
    "id": "rec-0116",
    "kind": "karar",
    "st": "onayli",
    "d": "Chris, please include this loss in today's notification letters to Ken Lay and Jeff Skilling...",
    "o": "Jeff Skilling",
    "os": "ratifier",
    "c": "high",
    "date": "2000-12-06",
    "sk": "dpr",
    "hl": "Chris, please include this loss in today's notification letters to Ken Lay and Jeff Skilling for the 5th. Per Oliver, the loss was due to power price curve shift and gas volatility curve shift against the Eastern spread options."
  },
  {
    "id": "rec-0118",
    "kind": "politika",
    "st": "onayli",
    "d": "European Gas - NOP and Maturity/Gap Limits revert to permanent limits on 1/1/01 (as previously...",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2000-12-12",
    "sk": "dpr",
    "hl": "European Gas - NOP and Maturity/Gap Limits revert to permanent limits on 1/1/01 (as previously scheduled), of 60 Bcf and 90 Bcf, respectively"
  },
  {
    "id": "rec-0120",
    "kind": "politika",
    "st": "onayli",
    "d": "Daily Loss in any Commodity group or Portfolio: Report to Business Unit Office of the Chairman...",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2000-12-12",
    "sk": "var",
    "hl": "Daily Loss in any Commodity group or Portfolio: Report to Business Unit Office of the Chairman 100% of VaR... Report to Enron Corp. President 125% of VaR... Report to Enron Corp. Chairman 150% of VaR... Report to Audit Committee no reporting at commodity group level",
    "chainTo": "rec-0070",
    "relType": "supersedes",
    "chainLabel": "rec-0120 (2000-12-12) Daily loss notification thresholds'ı revize ederken, rec-0070 (2000-06-12) eski eşikleri belirtmektedir;..."
  },
  {
    "id": "rec-0121",
    "kind": "politika",
    "st": "onayli",
    "d": "Cumulative 5-day Loss in any Commodity Group or Portfolio: Report to Business Unit Office of...",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2000-12-12",
    "sk": "var",
    "hl": "Cumulative 5-day Loss in any Commodity Group or Portfolio: Report to Business Unit Office of the Chairman 125% of VaR... Report to Enron Corp. President 150% of VaR... Report to Enron Corp. Chairman 175% of VaR... Report to Audit Committee no reporting at commodity group level",
    "chainTo": "rec-0070",
    "relType": "supersedes",
    "chainLabel": "rec-0121 (2000-12-12) 5-day cumulative loss notification thresholds'ı revize ederken, rec-0070 (2000-06-12) eski eşikleri..."
  },
  {
    "id": "rec-0035",
    "kind": "politika",
    "st": "onayli",
    "d": "UK Power's VaR and NOP are as follows: 1/1/01 - 1/5/01 UK Power VaR $13.95MM",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2000-12-19",
    "sk": "var",
    "hl": "UK Power's VaR and NOP are as follows: 1/1/01 - 1/5/01 UK Power VaR $13.95MM",
    "chainTo": "rec-0048",
    "relType": "conflicts",
    "chainLabel": "rec-0035 $13.95MM belirtirken, rec-0048 $18.95MM belirtmektedir (aynı dönem için çelişkili değerler)"
  },
  {
    "id": "rec-0048",
    "kind": "politika",
    "st": "onayli",
    "d": "UK Power $20.3MM $20.3MM $18.95MM $13.95MM",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2000-12-27",
    "sk": "var",
    "hl": "UK Power $20.3MM $20.3MM $18.95MM $13.95MM"
  },
  {
    "id": "rec-0055",
    "kind": "politika",
    "st": "onayli",
    "d": "UK Power 68 Twh 68 Twh 59.5 Twh 59.5 Twh",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2000-12-27",
    "sk": "limit",
    "hl": "UK Power 68 Twh 68 Twh 59.5 Twh 59.5 Twh"
  },
  {
    "id": "rec-0271",
    "kind": "politika",
    "st": "onayli",
    "d": "Pursuant to an Interoffice Memorandum from Jim Derrick to all Enron Attorneys dated October...",
    "o": "Mark Haedicke",
    "os": "policy",
    "c": "high",
    "date": "2001-01-31",
    "sk": "ops",
    "hl": "Pursuant to an Interoffice Memorandum from Jim Derrick to all Enron Attorneys dated October 27, 1999, I am required to seek approval from each of you prior to signing off on a non-solicitation agreement which affects Enron North America Corp."
  },
  {
    "id": "rec-0084",
    "kind": "karar",
    "st": "onayli",
    "d": "A separate e-mail was sent to each of your head traders and business unit controllers/CAO for...",
    "o": "Greg Whalley",
    "os": "ratifier",
    "c": "high",
    "date": "2001-02-13",
    "sk": "limit",
    "hl": "A separate e-mail was sent to each of your head traders and business unit controllers/CAO for each of these commodity groups with limit changes."
  },
  {
    "id": "rec-0091",
    "kind": "politika",
    "st": "onayli",
    "d": "Clarify the cross-commodity trading policy to specify that trading limits are to be applied...",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2001-02-13",
    "sk": "dpr",
    "hl": "Clarify the cross-commodity trading policy to specify that trading limits are to be applied against Enron's consolidated commodity positions on an individual commodity group basis; Enron's consolidated Daily Position Report should provide required market risk disclosures by primary commodity group"
  },
  {
    "id": "rec-0148",
    "kind": "politika",
    "st": "onayli",
    "d": "Note: if the shopping cart exceeds your spend limit, or contains fleet, stand-by or IT...",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2001-06-29",
    "sk": "limit",
    "hl": "Note: if the shopping cart exceeds your spend limit, or contains fleet, stand-by or IT hardware items it will require additional approval/review."
  },
  {
    "id": "rec-0171",
    "kind": "politika",
    "st": "onayli",
    "d": "2 risk policy issues came up - one regarding credit trading and the other regarding the...",
    "o": "Rick Buy",
    "os": "policy",
    "c": "high",
    "date": "2001-08-10",
    "sk": "credit",
    "hl": "2 risk policy issues came up - one regarding credit trading and the other regarding the freight book wanting to lay off credit risk with the credit book"
  },
  {
    "id": "rec-0177",
    "kind": "politika",
    "st": "onayli",
    "d": "The BOD approved an aggregate of $150MM, with $50MM of discretionary VaR, plus the new policy...",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2001-08-16",
    "sk": "var",
    "hl": "The BOD approved an aggregate of $150MM, with $50MM of discretionary VaR, plus the new policy which doesn't recognise the concept of discretionary VaR.",
    "chainTo": "rec-0180",
    "relType": "conflicts",
    "chainLabel": "rec-0177 $150MM aggregate + $50MM discretionary VaR belirtirken, rec-0180 discretionary VaR konseptini tanımlamadığını..."
  },
  {
    "id": "rec-0178",
    "kind": "politika",
    "st": "onayli",
    "d": "At Business Unit level the individual commodity limits are unchanged, and I have put limits...",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2001-08-16",
    "sk": "var",
    "hl": "At Business Unit level the individual commodity limits are unchanged, and I have put limits over the Business Units themselves as follows: Enron Americas $82MM, EWS OOC (aka George Martingale) $3MM, EEL $34MM, EGM $23MM, EIM $8MM, EBS $4MM, PGE $4MM, ETS $1MM.",
    "chainTo": "rec-0181",
    "relType": "conflicts",
    "chainLabel": "rec-0178 $82MM business unit seviyesi limit belirtirken, rec-0181 $100MM tek VaR limiti uygulanacağını belirtmektedir"
  },
  {
    "id": "rec-0180",
    "kind": "politika",
    "st": "onayli",
    "d": "Total trading was a loss of $106MM against a VaR limit of $150MM so no calls to Pug required...",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2001-08-16",
    "sk": "var",
    "hl": "Total trading was a loss of $106MM against a VaR limit of $150MM so no calls to Pug required (thank goodness)."
  },
  {
    "id": "rec-0181",
    "kind": "politika",
    "st": "onayli",
    "d": "Replace with one limit, expressed in VaR, for the entire business unit, of $100MM. ETL at this...",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2001-08-28",
    "sk": "var",
    "hl": "Replace with one limit, expressed in VaR, for the entire business unit, of $100MM. ETL at this level could be in the region of $340MM."
  },
  {
    "id": "rec-0188",
    "kind": "karar",
    "st": "onayli",
    "d": "Either Bill Kendrick or I will be touching base with her again, tomorrow. The EPA contact for...",
    "o": "Larry Campbell",
    "os": "ratifier",
    "c": "high",
    "date": "2001-09-10",
    "sk": "reg",
    "hl": "Either Bill Kendrick or I will be touching base with her again, tomorrow. The EPA contact for the Sta. 3 and 4 air permits: permit engineer Roger Cohn"
  },
  {
    "id": "rec-0186",
    "kind": "karar",
    "st": "onayli",
    "d": "Effective immediately, I want to sign all Dashes for RAC. I have asked Dave to continue...",
    "o": "Rick Buy",
    "os": "ratifier",
    "c": "high",
    "date": "2001-11-12",
    "sk": "dash",
    "hl": "Effective immediately, I want to sign all Dashes for RAC. I have asked Dave to continue reviewing the deals and initial the Dash but I want to sign them."
  },
  {
    "id": "rec-0192",
    "kind": "karar",
    "st": "onayli",
    "d": "After November 30, Enron will no longer match your savings plan contributions. As an...",
    "o": "",
    "os": "ratifier",
    "c": "high",
    "date": "2001-11-29",
    "sk": "people",
    "hl": "After November 30, Enron will no longer match your savings plan contributions. As an exception, the company will continue to match union employees' contributions to the Plan.",
    "chainTo": "rec-0193",
    "relType": "conflicts",
    "chainLabel": "rec-0192 30 Kasım'dan sonra şirket katkısı durdurulacağını belirtirken, rec-0193 30 Kasım bordrosundan kesilen katkıların nakit..."
  },
  {
    "id": "rec-0193",
    "kind": "politika",
    "st": "onayli",
    "d": "Savings Plan contributions that are deducted from your November 30 paycheck will be matched by...",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2001-11-29",
    "sk": "people",
    "hl": "Savings Plan contributions that are deducted from your November 30 paycheck will be matched by Enron in cash rather than Enron stock. The cash match will be placed into the Fidelity Freedom 2000 fund, the default fund for the Plan."
  },
  {
    "id": "rec-0194",
    "kind": "politika",
    "st": "onayli",
    "d": "Diversification within the Plan will now be allowed, regardless of your age, from ALL company...",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2001-11-29",
    "sk": "people",
    "hl": "Diversification within the Plan will now be allowed, regardless of your age, from ALL company contribution accounts... Effective immediately, you can invest these amounts in the fund or funds of your choosing."
  },
  {
    "id": "rec-0011",
    "kind": "karar",
    "st": "onayli",
    "d": "Earlier today, I stepped down as Enron's Chairman of the Board and Chief Executive Officer....",
    "o": "Ken Lay",
    "os": "ratifier",
    "c": "high",
    "date": "2002-01-24",
    "sk": "credit",
    "hl": "Earlier today, I stepped down as Enron's Chairman of the Board and Chief Executive Officer. This decision was reached in cooperation with Enron's Board and the Creditor Committee and is effective immediately. The Creditor Committee has begun a search for a restructuring specialist to serve as..."
  },
  {
    "id": "rec-0200",
    "kind": "politika",
    "st": "onayli",
    "d": "A vote will be taken to change the version 1.5 'GISB' standards to 'NAESB' standards... It...",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2002-02-20",
    "sk": "reg",
    "hl": "A vote will be taken to change the version 1.5 'GISB' standards to 'NAESB' standards... It will probably be a 17/2 vote... people will want to make it clear that this 17/2 vote should not be interpreted as a vote in favor of each and every standard. It is only a vote in favor of changing the...",
    "chainTo": "rec-0201",
    "relType": "conflicts",
    "chainLabel": "rec-0200 17/2 oylama prosedürü belirtirken, rec-0201 'onay' için Board'a sunulacağını belirtmektedir (prosedür tutarsızlığı)"
  },
  {
    "id": "rec-0201",
    "kind": "politika",
    "st": "onayli",
    "d": "The plan is to bring the response document before the Board at their March meeting for...",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2002-02-20",
    "sk": "reg",
    "hl": "The plan is to bring the response document before the Board at their March meeting for 'approval'. The response should also be reviewed by the Editorial Review Board... They may want the EC to approve the 'Executive Summary' and 'Conclusion' (total 3 pages). I have no problem with that vote except..."
  }
];
