// GERCEK Decdock kosusu - Enron kamuya acik FERC arsivi (250 mail -> curated proof subset).
const META = {
  "source": "decdock-enron-run2-moat",
  "sourceKind": "decdock.knowledge.raw.v1",
  "tenant": "enron-energy-trading",
  "generatedAt": "2026-07-02T10:53:36.725Z",
  "rawRecords": 316,
  "rawExtractedItems": 441,
  "rawConflicts": 6,
  "rawSupersedes": 22,
  "curatedRecords": 41,
  "keptConflicts": 5,
  "keptSupersedes": 2,
  "driftEdges": 7,
  "droppedConflicts": 1,
  "droppedSupersedes": 20,
  "honestyNote": "Supersedes edges are kept only when newer.sourceDate is later than older.sourceDate and the edge explanation is not a system heuristic. Borderline UK TWh and Mahonia sequence edges are dropped."
};

const SOURCES = {
  "limit": {
    "sub": "Trading limitleri",
    "body": "ENRON - kamuya acik e-posta arsivi (FERC)\nTrading limitleri\n\n[2000-04-10] Re: Limit Violation - Enron Australia\nit would be somewhat unprecedented to leave a \"proprietary\" position over the limit for that length of time, i.e., the Australian Electricity book would far exceed the number of position limit violations for any other commodities\n\n[2000-04-10] Re: Limit Violation - Enron Australia\nyou put together a request for approval to increase your limits to be presented at the first opportunity\n\n[2000-06-26] Quarter-end DPR Process\nAdjustments > $250,000 require approval from John Lavorato or John Sherriff.\n\n[2000-08-22] Re: Approval for Sign on Bonuses\nIf the sign on bonus amount is substantial then approval from David Oxley is advisable. In our current case, a $5,000.00 sign on for a Sr. Specialist would not require additional approval except your own.\n\n[2000-12-06] DPR and Loss Notification - \"Structured Derivatives\"\nChris, please include this loss in today's notification letters to Ken Lay and Jeff Skilling for the 5th. Per Oliver, the loss was due to power price curve shift and gas volatility curve shift against the Eastern spread options.\n\n[2001-02-13] Global Markets Limits\nA separate e-mail was sent to each of your head traders and business unit controllers/CAO for each of these commodity groups with limit changes."
  },
  "var": {
    "sub": "Risk / VaR",
    "body": "ENRON - kamuya acik e-posta arsivi (FERC)\nRisk / VaR\n\n[2000-06-12] Violation Memos Distribution\nDaily Loss 50% - 75% of VAR Limit > 75% of VAR Limit (VAR Limit = $40 MM); 5-Day Cumulative Loss 75% - 100% of VAR Limit > VAR Limit\n\n[2000-12-12] Enron Europe Limit Changes and DPR Reporting\nDaily Loss in any Commodity group or Portfolio: Report to Business Unit Office of the Chairman 100% of VaR... Report to Enron Corp. President 125% of VaR... Report to Enron Corp. Chairman 150% of VaR... Report to Audit Committee no reporting at commodity group level\n\n[2000-12-12] Enron Europe Limit Changes and DPR Reporting\nCumulative 5-day Loss in any Commodity Group or Portfolio: Report to Business Unit Office of the Chairman 125% of VaR... Report to Enron Corp. President 150% of VaR... Report to Enron Corp. Chairman 175% of VaR... Report to Audit Committee no reporting at commodity group level\n\n[2000-12-19] Upcoming Limit Changes- UK Power\nUK Power's VaR and NOP are as follows: 1/1/01 - 1/5/01 UK Power VaR $13.95MM\n\n[2000-12-27] Summary of Changes to Trading Limits 12/7 - 1/6\nUK Power $20.3MM $20.3MM $18.95MM $13.95MM\n\n[2001-08-16] Policy and other items\nThe BOD approved an aggregate of $150MM, with $50MM of discretionary VaR, plus the new policy which doesn't recognise the concept of discretionary VaR.\n\n[2001-08-16] Policy and other items\nAt Business Unit level the individual commodity limits are unchanged, and I have put limits over the Business Units themselves as follows: Enron Americas $82MM, EWS OOC (aka George Martingale) $3MM, EEL $34MM, EGM $23MM, EIM $8MM, EBS $4MM, PGE $4MM, ETS $1MM.\n\n[2001-08-16] Policy and other items\nTotal trading was a loss of $106MM against a VaR limit of $150MM so no calls to Pug required (thank goodness).\n\n[2001-08-28] Limit Revision - Enron Americas\nReplace with one limit, expressed in VaR, for the entire business unit, of $100MM. ETL at this level could be in the region of $340MM."
  },
  "dpr": {
    "sub": "DPR & kayip bildirimi",
    "body": "ENRON - kamuya acik e-posta arsivi (FERC)\nDPR & kayip bildirimi\n\n[2000-06-12] Violation Memos Distribution\nMark Frevert and Joe Sutton have asked to be copied on all violation memos and loss notification memos.\n\n[2000-06-26] Quarter-end DPR Process\nNO DPR will be issued dated July 3, 2000. For divisions reporting P&L for July 3rd and/or July 4th, a 'Special DPR' will be issued on July 5th... For consolidated DPR purposes, July 3rd and July 4th will be combined and reported as one day. These combined days will be reported as July 4th.\n\n[2000-12-06] DPR and Loss Notification - \"Structured Derivatives\"\nJames, perhaps you could work with Oliver and the commercial team to determine a reasonable methodology to support the allocation of P/L and related DPR reporting for these positions so we can continue to evaluate in compliance with the policy.\n\n[2001-02-13] NA Gas and Power Limits\nClarify the cross-commodity trading policy to specify that trading limits are to be applied against Enron's consolidated commodity positions on an individual commodity group basis; Enron's consolidated Daily Position Report should provide required market risk disclosures by primary commodity group\n\n[2001-04-04] Merchanting Metals Update #2\nan outline of the internal balance sheet review process described in my earlier note which must now be reprioritised and rescoped... reconciling differences between trader position analyses, AS400 on screen enquiries and the formal global position report ( these differences are at present not..."
  },
  "reg": {
    "sub": "Regulasyon",
    "body": "ENRON - kamuya acik e-posta arsivi (FERC)\nRegulasyon\n\n[2000-06-15] *** INTERRUPTIBLE CUSTOMERS CAN PARTICIPATE IN ISO A/S PROGRAM ***\nComments are due on June 27. Unless you tell us otherwise, we plan to file and seek expedited treatment... Both have asked for a July 17 effective date.\n\n[2000-07-01] TW Capacity Options meeting\nsales of options require Board approval at Enron\n\n[2001-09-10] Redrock Permit Issue, Requested Information\nEither Bill Kendrick or I will be touching base with her again, tomorrow. The EPA contact for the Sta. 3 and 4 air permits: permit engineer Roger Cohn\n\n[2002-02-20] NAESB EC Meeting\nA vote will be taken to change the version 1.5 'GISB' standards to 'NAESB' standards... It will probably be a 17/2 vote... people will want to make it clear that this 17/2 vote should not be interpreted as a vote in favor of each and every standard. It is only a vote in favor of changing the...\n\n[2002-02-20] NAESB EC Meeting\nThe plan is to bring the response document before the Board at their March meeting for 'approval'. The response should also be reviewed by the Editorial Review Board... They may want the EC to approve the 'Executive Summary' and 'Conclusion' (total 3 pages). I have no problem with that vote except..."
  },
  "ops": {
    "sub": "Operasyon",
    "body": "ENRON - kamuya acik e-posta arsivi (FERC)\nOperasyon\n\n[2000-10-09] Signature authority\nhe can approve but can't sign as a director. You need to continue to manage. This would take a board resolution to change\n\n[2000-12-04] Re: Northfield / Faribault Asset Divestiture Approval Form\nThe asset divestiture procedure requires approval from all officers before marketing/field services begin negotiations with potential buyers.\n\n[2001-01-31] Approval of a Non-Solicitation Provision\nPursuant to an Interoffice Memorandum from Jim Derrick to all Enron Attorneys dated October 27, 1999, I am required to seek approval from each of you prior to signing off on a non-solicitation agreement which affects Enron North America Corp."
  },
  "people": {
    "sub": "Atama & IK",
    "body": "ENRON - kamuya acik e-posta arsivi (FERC)\nAtama & IK\n\n[2000-10-16] Re: Koch Midstream Services Co\nwe may be putting ourselves in a risk area by 'assigning' the deals without proper documentation. The documentation that was supplied did not refence any ENA agreements, nor any specific meter numbers. If the purchase was indeed a meter/well sale; there should be documentation listing the meters...\n\n[2000-11-08] ETS Shuttle Plane Service\nminimum of 4 - 6, and/or the difficulty of reaching the destination(s) by commercial airlines... company plane usage requires the approval of your vice president. If employees are reserving individual available seats on a scheduled flight, vice presidential approval isn't required.\n\n[2001-06-08] Cost Savings Initiative\nThe URL/Web reference in the Professional Services section has been changed to http://ibuyit.enron.com/tibco. This is the URL for iBuyit. We are currently creating the content (FAQ's, procedures, forms, and etc.) that will be available via iBuyit to support the initiative.\n\n[2001-11-29] REVISED DRAFT - Savings Plan Memo\nAfter November 30, Enron will no longer match your savings plan contributions. As an exception, the company will continue to match union employees' contributions to the Plan.\n\n[2001-11-29] REVISED DRAFT - Savings Plan Memo\nSavings Plan contributions that are deducted from your November 30 paycheck will be matched by Enron in cash rather than Enron stock. The cash match will be placed into the Fidelity Freedom 2000 fund, the default fund for the Plan."
  },
  "credit": {
    "sub": "Counterparty / kredi",
    "body": "ENRON - kamuya acik e-posta arsivi (FERC)\nCounterparty / kredi\n\n[2000-10-26] OGC/AGC Approval Policy for More Than One Year Contracts\nIf a master is in place, confirmations will be used for terms of one month to greater than one year. I don't think it will be practical for us to approve these confirmations before signature unless there are material modifications done to the pre-approved confirmation template in the master, which...\n\n[2001-08-10] London Update\n2 risk policy issues came up - one regarding credit trading and the other regarding the freight book wanting to lay off credit risk with the credit book\n\n[2002-01-24] Message from Ken Lay\nEarlier today, I stepped down as Enron's Chairman of the Board and Chief Executive Officer. This decision was reached in cooperation with Enron's Board and the Creditor Committee and is effective immediately. The Creditor Committee has begun a search for a restructuring specialist to serve as..."
  },
  "dash": {
    "sub": "DASH deal onayi",
    "body": "ENRON - kamuya acik e-posta arsivi (FERC)\nDASH deal onayi\n\n[2000-11-13] Deal Approval Sheet (DASH) Process\nCapital expenditures include any acquisitions/divestitures of assets, offerings of debt, subordinated debt, equity or partnership capital or entering into a commodity or financial position that results in an exposure outside of Board approved limits. Capital expenditure amounts embedded in a...\n\n[2000-11-14] Deal Approval Sheet (DASH) Process for EGM\nentering into a commodity or financial position that results in an exposure outside of Board approved limits. Capital expenditure amounts embedded in a commodity price to a counterparty should be analyzed separately for DASH purposes and authorized by the appropriate entity\n\n[2001-05-11] Plan to Rebuild the Business\nDevelop Form Approval Process -- dual approvals by EES and ENA. Develop Deal Approval Process -- deals above a certain size (or material variations from the form) would require concurrent EWS approval\n\n[2001-05-14] Plan to Rebuild the Business\nDevelop Form Approval Process -- dual approvals by EES and ENA. Develop Deal Approval Process -- deals above a certain size (or material variations from the form) would require concurrent EWS approval\n\n[2001-11-12] Dash Sign Off\nEffective immediately, I want to sign all Dashes for RAC. I have asked Dave to continue reviewing the deals and initial the Dash but I want to sign them."
  }
};

const DATA = [
  {
    "id": "rec-0078",
    "kind": "politika",
    "st": "onayli",
    "d": "Pozisyon limit ihlallerinin uzun süreli (Board onayı öncesi) devam etmesi önceden görülmemiş...",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2000-04-10",
    "sk": "limit",
    "hl": "it would be somewhat unprecedented to leave a \"proprietary\" position over the limit for that length of time, i.e., the Australian Electricity book would far exceed the number of position limit violations for any other commodities"
  },
  {
    "id": "rec-0080",
    "kind": "karar",
    "st": "onayli",
    "d": "Paul Quilkey (Enron Development) limit artışı talebini hazırlamaktan sorumludur. Ted Murphy...",
    "o": "Rick Buy",
    "os": "ratifier",
    "c": "high",
    "date": "2000-04-10",
    "sk": "limit",
    "hl": "you put together a request for approval to increase your limits to be presented at the first opportunity"
  },
  {
    "id": "rec-0070",
    "kind": "politika",
    "st": "onayli",
    "d": "Loss notification memos zorunlu: Günlük zarar %50-75 VaR limitinin (VaR Limit=$40MM) arasında...",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2000-06-12",
    "sk": "var",
    "hl": "Daily Loss 50% - 75% of VAR Limit > 75% of VAR Limit (VAR Limit = $40 MM); 5-Day Cumulative Loss 75% - 100% of VAR Limit > VAR Limit"
  },
  {
    "id": "rec-0071",
    "kind": "karar",
    "st": "onayli",
    "d": "Mark Frevert ve Joe Sutton tüm violation memos ve loss notification memos'a CC alınacak.",
    "o": "Mark Frevert",
    "os": "ratifier",
    "c": "high",
    "date": "2000-06-12",
    "sk": "dpr",
    "hl": "Mark Frevert and Joe Sutton have asked to be copied on all violation memos and loss notification memos."
  },
  {
    "id": "rec-0006",
    "kind": "politika",
    "st": "onayli",
    "d": "Utilities filed advice letters with CPUC. Comment deadline: June 27, 2000. Enron plans to file...",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2000-06-15",
    "sk": "reg",
    "hl": "Comments are due on June 27. Unless you tell us otherwise, we plan to file and seek expedited treatment... Both have asked for a July 17 effective date."
  },
  {
    "id": "rec-0063",
    "kind": "karar",
    "st": "onayli",
    "d": "$250,000 üzerindeki ayarlamalar John Lavorato veya John Sherriff onayı gerektirir.",
    "o": "John Lavorato",
    "os": "ratifier",
    "c": "high",
    "date": "2000-06-26",
    "sk": "limit",
    "hl": "Adjustments > $250,000 require approval from John Lavorato or John Sherriff."
  },
  {
    "id": "rec-0064",
    "kind": "politika",
    "st": "onayli",
    "d": "July 3 tarihli DPR yayınlanmaz. July 3-4 için P&L raporlayan bölümler için 'Special DPR' July...",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2000-06-26",
    "sk": "dpr",
    "hl": "NO DPR will be issued dated July 3, 2000. For divisions reporting P&L for July 3rd and/or July 4th, a 'Special DPR' will be issued on July 5th... For consolidated DPR purposes, July 3rd and July 4th will be combined and reported as one day. These combined days will be reported as July 4th."
  },
  {
    "id": "rec-0310",
    "kind": "politika",
    "st": "onayli",
    "d": "Kapasite opsiyonlarının satışı Enron Yönetim Kurulu onayı gerektirir. Satış öncesi aşamalar:...",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2000-07-01",
    "sk": "reg",
    "hl": "sales of options require Board approval at Enron"
  },
  {
    "id": "rec-0020",
    "kind": "karar",
    "st": "onayli",
    "d": "Sr. Specialist pozisyonuna verilen $5,000 veya daha düşük sign-on bonus için Sally Beck'in...",
    "o": "Sally Beck",
    "os": "ratifier",
    "c": "high",
    "date": "2000-08-22",
    "sk": "limit",
    "hl": "If the sign on bonus amount is substantial then approval from David Oxley is advisable. In our current case, a $5,000.00 sign on for a Sr. Specialist would not require additional approval except your own."
  },
  {
    "id": "rec-0269",
    "kind": "politika",
    "st": "onayli",
    "d": "Yönetici imza yetkisi değişiklikleri Yönetim Kurulu kararı gerektirir. Operasyonel onay...",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2000-10-09",
    "sk": "ops",
    "hl": "he can approve but can't sign as a director. You need to continue to manage. This would take a board resolution to change"
  },
  {
    "id": "rec-0295",
    "kind": "politika",
    "st": "onayli",
    "d": "Uygun dokümantasyon olmaksızın anlaşmaları 'assign' etmek risk alanına girebilir. Meter/well...",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2000-10-16",
    "sk": "people",
    "hl": "we may be putting ourselves in a risk area by 'assigning' the deals without proper documentation. The documentation that was supplied did not refence any ENA agreements, nor any specific meter numbers. If the purchase was indeed a meter/well sale; there should be documentation listing the meters..."
  },
  {
    "id": "rec-0398",
    "kind": "politika",
    "st": "onayli",
    "d": "OGC/AGC approval required for individually negotiated contracts with term greater than one...",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2000-10-26",
    "sk": "credit",
    "hl": "If a master is in place, confirmations will be used for terms of one month to greater than one year. I don't think it will be practical for us to approve these confirmations before signature unless there are material modifications done to the pre-approved confirmation template in the master, which..."
  },
  {
    "id": "rec-0326",
    "kind": "politika",
    "st": "onayli",
    "d": "Enron uçağı kullanımı için minimum 4-6 yolcu veya ticari uçakla ulaşılması zor destinasyonlar...",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2000-11-08",
    "sk": "people",
    "hl": "minimum of 4 - 6, and/or the difficulty of reaching the destination(s) by commercial airlines... company plane usage requires the approval of your vice president. If employees are reserving individual available seats on a scheduled flight, vice presidential approval isn't required."
  },
  {
    "id": "rec-0124",
    "kind": "politika",
    "st": "onayli",
    "d": "Emtia fiyatına gömülü sermaye harcaması tutarları DASH amaçları için ayrı analiz edilmeli ve...",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2000-11-13",
    "sk": "dash",
    "hl": "Capital expenditures include any acquisitions/divestitures of assets, offerings of debt, subordinated debt, equity or partnership capital or entering into a commodity or financial position that results in an exposure outside of Board approved limits. Capital expenditure amounts embedded in a..."
  },
  {
    "id": "rec-0394",
    "kind": "politika",
    "st": "onayli",
    "d": "Kurul tarafından onaylanan limitler dışında bir maruz kalma ile sonuçlanan emtia veya finansal...",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2000-11-14",
    "sk": "dash",
    "hl": "entering into a commodity or financial position that results in an exposure outside of Board approved limits. Capital expenditure amounts embedded in a commodity price to a counterparty should be analyzed separately for DASH purposes and authorized by the appropriate entity"
  },
  {
    "id": "rec-0420",
    "kind": "politika",
    "st": "onayli",
    "d": "Pazarlama ve saha hizmetleri (marketing/field services) potansiyel alıcılarla müzakerelere...",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2000-12-04",
    "sk": "ops",
    "hl": "The asset divestiture procedure requires approval from all officers before marketing/field services begin negotiations with potential buyers."
  },
  {
    "id": "rec-0115",
    "kind": "karar",
    "st": "onayli",
    "d": "James New (LON/ECT) sorumlu: Oliver Gaylard ve commercial team ile birlikte P/L ve DPR...",
    "o": "",
    "os": "ratifier",
    "c": "high",
    "date": "2000-12-06",
    "sk": "dpr",
    "hl": "James, perhaps you could work with Oliver and the commercial team to determine a reasonable methodology to support the allocation of P/L and related DPR reporting for these positions so we can continue to evaluate in compliance with the policy."
  },
  {
    "id": "rec-0116",
    "kind": "karar",
    "st": "onayli",
    "d": "Chris Abel (HOU/ECT) tarafından Ken Lay ve Jeff Skilling'e Loss Notification mektubu...",
    "o": "Jeff Skilling",
    "os": "ratifier",
    "c": "high",
    "date": "2000-12-06",
    "sk": "limit",
    "hl": "Chris, please include this loss in today's notification letters to Ken Lay and Jeff Skilling for the 5th. Per Oliver, the loss was due to power price curve shift and gas volatility curve shift against the Eastern spread options."
  },
  {
    "id": "rec-0120",
    "kind": "politika",
    "st": "onayli",
    "d": "Daily loss reporting escalation: (1) Business Unit Office of the Chairman at 100% of VaR; (2)...",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2000-12-12",
    "sk": "var",
    "hl": "Daily Loss in any Commodity group or Portfolio: Report to Business Unit Office of the Chairman 100% of VaR... Report to Enron Corp. President 125% of VaR... Report to Enron Corp. Chairman 150% of VaR... Report to Audit Committee no reporting at commodity group level",
    "chainTo": "rec-0070",
    "relType": "supersedes",
    "chainLabel": "rec-0120 (2000-12-12) Daily loss notification thresholds'ı revize ederken, rec-0070 (2000-06-12) eski eşikleri belirtmektedir;..."
  },
  {
    "id": "rec-0121",
    "kind": "politika",
    "st": "onayli",
    "d": "5-day cumulative loss reporting escalation: (1) Business Unit Office of the Chairman at 125%...",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2000-12-12",
    "sk": "var",
    "hl": "Cumulative 5-day Loss in any Commodity Group or Portfolio: Report to Business Unit Office of the Chairman 125% of VaR... Report to Enron Corp. President 150% of VaR... Report to Enron Corp. Chairman 175% of VaR... Report to Audit Committee no reporting at commodity group level",
    "chainTo": "rec-0070",
    "relType": "supersedes",
    "chainLabel": "rec-0121 (2000-12-12) 5-day cumulative loss notification thresholds'ı revize ederken, rec-0070 (2000-06-12) eski eşikleri..."
  },
  {
    "id": "rec-0035",
    "kind": "politika",
    "st": "onayli",
    "d": "UK Power VaR limiti 1/1/01 - 1/5/01 döneminde $13.95MM olarak belirlendi (12/23/00 - 12/31/00...",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2000-12-19",
    "sk": "var",
    "hl": "UK Power's VaR and NOP are as follows: 1/1/01 - 1/5/01 UK Power VaR $13.95MM",
    "chainTo": "rec-0048",
    "relType": "conflicts",
    "chainLabel": "rec-0035 $13.95MM belirtirken, rec-0048 $18.95MM belirtmektedir (aynı dönem için çelişkili değerler)"
  },
  {
    "id": "rec-0048",
    "kind": "politika",
    "st": "onayli",
    "d": "VaR limiti $18.95MM (azalış)",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2000-12-27",
    "sk": "var",
    "hl": "UK Power $20.3MM $20.3MM $18.95MM $13.95MM"
  },
  {
    "id": "rec-0271",
    "kind": "politika",
    "st": "onayli",
    "d": "Jim Derrick'in 27 Ekim 1999 tarihli Interoffice Memorandum'una göre, Enron North America...",
    "o": "Mark Haedicke",
    "os": "policy",
    "c": "high",
    "date": "2001-01-31",
    "sk": "ops",
    "hl": "Pursuant to an Interoffice Memorandum from Jim Derrick to all Enron Attorneys dated October 27, 1999, I am required to seek approval from each of you prior to signing off on a non-solicitation agreement which affects Enron North America Corp."
  },
  {
    "id": "rec-0084",
    "kind": "karar",
    "st": "onayli",
    "d": "Cassandra Schultz (cassandra.schultz@enron.com) tarafından Jeffrey Shankman, Greg Whalley,...",
    "o": "Greg Whalley",
    "os": "ratifier",
    "c": "high",
    "date": "2001-02-13",
    "sk": "limit",
    "hl": "A separate e-mail was sent to each of your head traders and business unit controllers/CAO for each of these commodity groups with limit changes."
  },
  {
    "id": "rec-0091",
    "kind": "politika",
    "st": "onayli",
    "d": "Trading limits applied against Enron's consolidated commodity positions on individual...",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2001-02-13",
    "sk": "dpr",
    "hl": "Clarify the cross-commodity trading policy to specify that trading limits are to be applied against Enron's consolidated commodity positions on an individual commodity group basis; Enron's consolidated Daily Position Report should provide required market risk disclosures by primary commodity group"
  },
  {
    "id": "rec-0095",
    "kind": "politika",
    "st": "onayli",
    "d": "İç bilançosu inceleme süreci yeniden öncelendirilmeli ve yeniden kapsamlandırılmalıdır. Trader...",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2001-04-04",
    "sk": "dpr",
    "hl": "an outline of the internal balance sheet review process described in my earlier note which must now be reprioritised and rescoped... reconciling differences between trader position analyses, AS400 on screen enquiries and the formal global position report ( these differences are at present not..."
  },
  {
    "id": "rec-0384",
    "kind": "politika",
    "st": "onayli",
    "d": "Form Onay Süreci: EES ve ENA tarafından çift onay (dual approvals) gerekli. Belirli...",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2001-05-11",
    "sk": "dash",
    "hl": "Develop Form Approval Process -- dual approvals by EES and ENA. Develop Deal Approval Process -- deals above a certain size (or material variations from the form) would require concurrent EWS approval"
  },
  {
    "id": "rec-0386",
    "kind": "politika",
    "st": "onayli",
    "d": "Form Onay Süreci: EES ve ENA tarafından çift onay (dual approvals) gerekli. Belirli...",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2001-05-14",
    "sk": "dash",
    "hl": "Develop Form Approval Process -- dual approvals by EES and ENA. Develop Deal Approval Process -- deals above a certain size (or material variations from the form) would require concurrent EWS approval"
  },
  {
    "id": "rec-0275",
    "kind": "politika",
    "st": "onayli",
    "d": "Profesyonel Hizmetler için iBuyit platformu (http://ibuyit.enron.com/tibco) kullanılacak....",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2001-06-08",
    "sk": "people",
    "hl": "The URL/Web reference in the Professional Services section has been changed to http://ibuyit.enron.com/tibco. This is the URL for iBuyit. We are currently creating the content (FAQ's, procedures, forms, and etc.) that will be available via iBuyit to support the initiative."
  },
  {
    "id": "rec-0171",
    "kind": "politika",
    "st": "onayli",
    "d": "İki risk politikası konusu tanımlanmış: (1) kredi ticareti politikası, (2) kargo kitabının...",
    "o": "Rick Buy",
    "os": "policy",
    "c": "high",
    "date": "2001-08-10",
    "sk": "credit",
    "hl": "2 risk policy issues came up - one regarding credit trading and the other regarding the freight book wanting to lay off credit risk with the credit book"
  },
  {
    "id": "rec-0177",
    "kind": "politika",
    "st": "onayli",
    "d": "BOD onaylı toplam VaR limiti $150MM (aggregate), içinde $50MM discretionary VaR. Yeni politika...",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2001-08-16",
    "sk": "var",
    "hl": "The BOD approved an aggregate of $150MM, with $50MM of discretionary VaR, plus the new policy which doesn't recognise the concept of discretionary VaR.",
    "chainTo": "rec-0180",
    "relType": "conflicts",
    "chainLabel": "rec-0177 $150MM aggregate + $50MM discretionary VaR belirtirken, rec-0180 discretionary VaR konseptini tanımlamadığını..."
  },
  {
    "id": "rec-0178",
    "kind": "politika",
    "st": "onayli",
    "d": "Business Unit seviyesi VaR limitleri: Enron Americas $82MM, EWS OOC $3MM, EEL $34MM, EGM...",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2001-08-16",
    "sk": "var",
    "hl": "At Business Unit level the individual commodity limits are unchanged, and I have put limits over the Business Units themselves as follows: Enron Americas $82MM, EWS OOC (aka George Martingale) $3MM, EEL $34MM, EGM $23MM, EIM $8MM, EBS $4MM, PGE $4MM, ETS $1MM.",
    "chainTo": "rec-0181",
    "relType": "conflicts",
    "chainLabel": "rec-0178 $82MM business unit seviyesi limit belirtirken, rec-0181 $100MM tek VaR limiti uygulanacağını belirtmektedir"
  },
  {
    "id": "rec-0180",
    "kind": "politika",
    "st": "onayli",
    "d": "Toplam ticaret VaR limiti ($150MM) aşılması durumunda Pug'a (muhtemelen CFO/Risk Committee...",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2001-08-16",
    "sk": "var",
    "hl": "Total trading was a loss of $106MM against a VaR limit of $150MM so no calls to Pug required (thank goodness)."
  },
  {
    "id": "rec-0181",
    "kind": "politika",
    "st": "onayli",
    "d": "Hacimsel limitler (net açık pozisyon, vade farkı) ve bireysel emtia limitlerini kaldırarak,...",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2001-08-28",
    "sk": "var",
    "hl": "Replace with one limit, expressed in VaR, for the entire business unit, of $100MM. ETL at this level could be in the region of $340MM."
  },
  {
    "id": "rec-0188",
    "kind": "karar",
    "st": "onayli",
    "d": "Larry Campbell and Bill Kendrick are responsible for regulatory liaison and permit approval...",
    "o": "Larry Campbell",
    "os": "ratifier",
    "c": "high",
    "date": "2001-09-10",
    "sk": "reg",
    "hl": "Either Bill Kendrick or I will be touching base with her again, tomorrow. The EPA contact for the Sta. 3 and 4 air permits: permit engineer Roger Cohn"
  },
  {
    "id": "rec-0186",
    "kind": "karar",
    "st": "onayli",
    "d": "Rick Buy, RAC için tüm Dash imzalamalarının sorumluluğunu üstlenmektedir. Dave, işlemleri...",
    "o": "Rick Buy",
    "os": "ratifier",
    "c": "high",
    "date": "2001-11-12",
    "sk": "dash",
    "hl": "Effective immediately, I want to sign all Dashes for RAC. I have asked Dave to continue reviewing the deals and initial the Dash but I want to sign them."
  },
  {
    "id": "rec-0192",
    "kind": "karar",
    "st": "onayli",
    "d": "Enron Yönetim Kurulu 28 Kasım 2001'de Savings Plan değişikliğini onayladı. 30 Kasım'dan sonra...",
    "o": "",
    "os": "ratifier",
    "c": "high",
    "date": "2001-11-29",
    "sk": "people",
    "hl": "After November 30, Enron will no longer match your savings plan contributions. As an exception, the company will continue to match union employees' contributions to the Plan.",
    "chainTo": "rec-0193",
    "relType": "conflicts",
    "chainLabel": "rec-0192 30 Kasım'dan sonra şirket katkısı durdurulacağını belirtirken, rec-0193 30 Kasım bordrosundan kesilen katkıların nakit..."
  },
  {
    "id": "rec-0193",
    "kind": "politika",
    "st": "onayli",
    "d": "30 Kasım bordrosundan kesilen katkılar nakit olarak eşleştirilecek (hisse senedi yerine) ve...",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2001-11-29",
    "sk": "people",
    "hl": "Savings Plan contributions that are deducted from your November 30 paycheck will be matched by Enron in cash rather than Enron stock. The cash match will be placed into the Fidelity Freedom 2000 fund, the default fund for the Plan."
  },
  {
    "id": "rec-0011",
    "kind": "karar",
    "st": "onayli",
    "d": "Ken Lay, Enron Yönetim Kurulu Başkanı ve CEO pozisyonundan istifa etmiştir (23 Ocak 2002...",
    "o": "Ken Lay",
    "os": "ratifier",
    "c": "high",
    "date": "2002-01-24",
    "sk": "credit",
    "hl": "Earlier today, I stepped down as Enron's Chairman of the Board and Chief Executive Officer. This decision was reached in cooperation with Enron's Board and the Creditor Committee and is effective immediately. The Creditor Committee has begun a search for a restructuring specialist to serve as..."
  },
  {
    "id": "rec-0200",
    "kind": "politika",
    "st": "onayli",
    "d": "17/2 oylama prosedürü kullanılacak. Oylamanın GISB'den NAESB standartlarına geçişi onayladığı,...",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2002-02-20",
    "sk": "reg",
    "hl": "A vote will be taken to change the version 1.5 'GISB' standards to 'NAESB' standards... It will probably be a 17/2 vote... people will want to make it clear that this 17/2 vote should not be interpreted as a vote in favor of each and every standard. It is only a vote in favor of changing the...",
    "chainTo": "rec-0201",
    "relType": "conflicts",
    "chainLabel": "rec-0200 17/2 oylama prosedürü belirtirken, rec-0201 'onay' için Board'a sunulacağını belirtmektedir (prosedür tutarsızlığı)"
  },
  {
    "id": "rec-0201",
    "kind": "politika",
    "st": "onayli",
    "d": "Yanıt belgesi Mart ayında Yönetim Kurulu'na 'onay' için sunulacak. Belgeler ayrıca Editorial...",
    "o": "",
    "os": "policy",
    "c": "high",
    "date": "2002-02-20",
    "sk": "reg",
    "hl": "The plan is to bring the response document before the Board at their March meeting for 'approval'. The response should also be reviewed by the Editorial Review Board... They may want the EC to approve the 'Executive Summary' and 'Conclusion' (total 3 pages). I have no problem with that vote except..."
  }
];
